name: Data Imaginist
description: Visualization, Data Science, and Biology
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://www.data-imaginist.com'
google_analytics: 'UA-84380701-1'
disqus: false
disqus_shortname: 'thomaslinpedersen'

# Details for the RSS feed generator
url:            'http://www.data-imaginist.com'
author:         'Thomas Lin Pedersen'
authorTwitter:  'thomasp85'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
            large_thumb: false
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            author: Thomas Lin Pedersen
            large_thumb: false
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
            author: Thomas Lin Pedersen
            large_thumb: false
